### ISSUE TITLE
Read Data

### ISSUE THREAD

**Issue by MuhammetAdamoglu** [flyskywhy/react-native-usb-serialport#1]
How can I read data via USB port?
I have a USB-connected barcode reader. It sends the barcode number read through the usb port.

**Comment by flyskywhy** [comment]
In the README.md -> Documents -> `Auto Connection` or `Manual Connection`
ref to the code:

    DeviceEventEmitter.addListener(actions.ON_READ_DATA, this.onReadData, this);
