### ISSUE TITLE
Upgrade dependency on react-native

### ISSUE THREAD

**Issue by lr210** [flyskywhy/react-native-usb-serialport#10]
Would it be possible to upgrade the dependency for this project so that it is compatible with newer react-native versions?

**Comment by flyskywhy** [comment]
Do you mean #9 ?

**Comment by lr210** [comment]
No, I think this issue is the same as #2, apologies

**Comment by flyskywhy** [comment]
I just removed `peerDependencies` in `react-native-usb-serialport@2.3.4`, is that your need?

**Comment by lr210** [comment]
That's great, thank you!
