### ISSUE TITLE
instalation

### ISSUE THREAD

**Issue by steve-lgtm** [flyskywhy/react-native-usb-serialport#12]
What are instalation steps ?

**Comment by steve-lgtm** [comment]
**install with yarn or npm:**
npm i react-native-usb-serialport

**and fix error with build guava:**
You can add this to your android/app/bundle.gradle dependencies
implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'

**Comment by flyskywhy** [comment]
With `react-native-usb-serialport@2.3.5`, no more need 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
