### ISSUE TITLE
got 1 argument expected 2

### ISSUE THREAD

**Issue by steve-lgtm** [flyskywhy/react-native-usb-serialport#13]
Hi @flyskywhy !

Can you help me with that?

![image](https://user-images.githubusercontent.com/60081152/235269348-c1c5138b-a72b-4fe6-afef-332f3903d805.png)

**Comment by TheGlenn88** [comment]
Dupe of #4 
you need to use:

```javascript
RNSerialport.writeString("/dev/bus/usb/001/002", "hello");
```

This is explained in the README, search for "diff" to find it.

**Comment by steve-lgtm** [comment]
Yeah I see it's working now. Thanks
