### ISSUE TITLE
splitting read data

### ISSUE THREAD

**Issue by steve-lgtm** [flyskywhy/react-native-usb-serialport#14]
When I receiving data from USB, it seems that data are splited.

![image](https://github.com/flyskywhy/react-native-usb-serialport/assets/60081152/c180737d-5c2c-49bc-9f8a-831ada9187e7)

Where is problem ?

**Comment by flyskywhy** [comment]
I think you need ref to onReadData to see if definitions.RETURNED_DATA_TYPES.INTARRAY or definitions.RETURNED_DATA_TYPES.HEXSTRING in <https://github.com/melihyarikkaya/react-native-serialport/wiki/Auto-Connection>
