### ISSUE TITLE
TARGETING S+ requires one of FLAG_IMMUTABLE or FLAG_MUTABLE

### ISSUE THREAD

**Issue by PelePeluche** [flyskywhy/react-native-usb-serialport#15]
When attempting to

```javascript

await UsbSerialManager.tryRequestPermission(
      someId
    )
```    
I receive the following error:

[screnshoot error](https://i.stack.imgur.com/Nt0Kc.jpg)

**Comment by flyskywhy** [comment]
Resolved in `react-native-usb-serialport@3.0.0`
