### ISSUE TITLE
Assemble release Issue

### ISSUE THREAD

**Issue by Florent75** [flyskywhy/react-native-usb-serialport#16]
Hi there,

I have an issue when creating release using the ./gradlew assembleRelease command line.
I have the following  error when launching the command line : 

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-usb-serialport:bundleReleaseLocalLintAar'.
> Error while evaluating property 'hasLocalAarDeps' of task ':react-native-usb-serialport:bundleReleaseLocalLintAar'
   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-usb-serialport project caused this error: 
node_modules/react-native-usb-serialport/android/libs/usbserial-6.0.5-release.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

In other package it  seems to be related to gradle package.
here is my config : 
        "react": "18.2.0",
        "react-native": "0.71.0",
        "react-native-usb-serialport": "^2.3.5",

In case it's interesting :  
**grade-wrapper.properties**
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

**android/build.gradle**
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

Could you give me some hint on how to solve it ?

thanks

**Comment by flyskywhy** [comment]
I tried before but failed, hope someone can offer a PR...

**Comment by Florent75** [comment]
I have found a solution : 
https://github.com/melihyarikkaya/react-native-serialport/issues/41

EDIT : 
0 - Do what is recommended in the link

Plus : 
1 - be sure of having creating the libs directory in Android directory (or Android/app directory)
2 - You should add the following line in Android/build.gradle file in dependency sections : 
    implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])
3 - Clean release ./gradlew clean
4 - Rebuild using ./gradlew app:assembleRelease

Let me know but working on my side now !

**Comment by flyskywhy** [comment]
Resolved in `react-native-usb-serialport@3.0.0`

**Comment by soilabAI** [comment]
thank you so much for this fix
