### ISSUE TITLE
[Error: No driver for device]

### ISSUE THREAD

**Issue by sharkboy777** [flyskywhy/react-native-usb-serialport#17]
[Error: No driver for device]

Receiving the above error while trying to open the serial port after giving all the permissions.

**Comment by usmananypos** [comment]
Hi, have resolved that issue? I am also encountering this issue however i am getting deviceName etc

**Comment by flyskywhy** [comment]
Do you guy uncomment the `console.warn(list)` in `fillDeviceListAndConnect()` and have a look at the result? Maybe you need adjust the `item.vendorId === 6790` if your device is not`ch34x`
