### ISSUE TITLE
Cannot set property 'intArrayToUtf16' of null

### ISSUE THREAD

**Issue by gab-logicbase** [flyskywhy/react-native-usb-serialport#18]
when I install the package and import the library with just the following:

import { RNSerialport, definitions, actions } from "react-native-usb-serialport";

it will show the following error:

![image](https://github.com/flyskywhy/react-native-usb-serialport/assets/116131283/81a7c015-b6e6-49ad-bff1-eb2ffa6afd35)

**Comment by flyskywhy** [comment]
It''s saying `RNSerialport` is null, so why your `RNSerialport` is null? Did you complile the android code?

**Comment by flyskywhy** [comment]
Are you run on iOS then meat the issue? If so, maybe you can try the code in this commit https://github.com/Roga-life/react-native-serialport/commit/21fbfa0243f1b8647a02d3f6076248bca26829a3 , and tell me the result.

**Comment by anandkumar-omnipay** [comment]
I am facing the same issue. I am running the project in expo android @flyskywhy

**Comment by flyskywhy** [comment]
> I am facing the same issue. I am running the project in expo android @flyskywhy

Make a test: just delete `intArrayToUtf16` and `hexToUtf16` source code in `node_modules/react-native-usb-serialport/index.js`, then is your APP can use `RNSerialport` other method e.g. `startUsbService()` normally? Or still say `RNSerialport` is null?

Please tell me the test result.
