### ISSUE TITLE
Refactor and test turbomodule

### ISSUE THREAD

**Issue by SerSerch** [flyskywhy/react-native-usb-serialport#19]
Hello! I decided to try to write this module using turbomodules.
But so far I have a lot of errors when starting android.
I'm not good at java. If you have free time, I would be glad if you could help me with this.

## [refactor](https://github.com/serserm/react-native-usb-serialport/tree/turbomodule)

```
yarn@4.1.0
gradle:7.2.1
minSdkVersion=23
targetSdkVersion=34
compileSdkVersion=34
newArchEnabled=true
```

* update packages
* add config monorepo
* add typescript
* add turbomodule
* add lerna
* add example

### Using in root repo

* install
```bash
yarn
```
* build js to `/lib`
```bash
yarn build
```
* start example metro server
```bash
yarn start
```
* start example in android
```bash
yarn android
```
* [turbomodule codegen](https://reactnative.dev/docs/the-new-architecture/pillars-turbomodules#android)
```bash
yarn example codegen
```
* update version and release module to npm
```bash
yarn release
```
* imports
```javascript
import {
 RNSerialport,
 actions,
 definitions,
 createServer,
 createConnection,
 Server,
 Socket,
 intArrayToUtf16,
 hexToUtf16,
} from 'react-native-usb-serialport';
```

**Comment by flyskywhy** [comment]
Sorry, I'm not good at turbomodule, and no plan to rewrite the repo with it.
