### ISSUE TITLE
npm installation version problem

### ISSUE THREAD

**Issue by requiem-projects** [flyskywhy/react-native-usb-serialport#2]
Hi, 
I use a fresh react native project in version 0.64
When installing react-native-usb-serialport I encountered a dependency error :  

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test6@0.0.1
npm ERR! Found: react-native@0.64.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.59.0" from react-native-usb-serialport@2.1.1
npm ERR! node_modules/react-native-usb-serialport
npm ERR!   react-native-usb-serialport@"*" from the root project

How Can I resolve this error ? I'm new in react Native.
Is the 0.59 version is important ? or can I patch the package.json to accept 0.64 version of react Native ?

**Comment by flyskywhy** [comment]
According to npm semver rule, `^` is compatible with 0.59.0 and 0.64.2, so this issue strange.

I just run

    react-native init foobar --version 0.64.2
    cd foobar
    npm install react-native-usb-serialport

and no problem.

Only `npm WARN`

    npm WARN react-native-usb-serialport@2.1.1 requires a peer of react-native@^0.59.0 but none is installed. You must install peer dependencies yourself.

No `npm ERR! `

My env:

    Linux
    npm 6.14.4
    node v10.15.3

What's your env?
And, more important, what's your `npm config list`?

**Comment by requiem-projects** [comment]
my env is 
npm 7.5.6
node V12.13.1

I had just try to switch to the same version like your env, but I have error too (different) : npm 6.9 and node v10.15.3

`
error react-native@0.64.2: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.15.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
(node:27152) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react@17.0.1
    at makeError (/home/jfg/perso/reactnative/test/rnvtest/foobar/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/jfg/perso/reactnative/test/rnvtest/foobar/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:27152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

npm config list : 
`; "user" config from /home/jfg/.npmrc

//registry.npmjs.org/:_authToken = (protected) 
registry = "https://registry.npmjs.org/" 

; "cli" config from command line options

omit = [] 
user-agent = "npm/7.5.6 node/v12.13.1 linux x64" 

; node bin location = /home/jfg/.nvm/versions/node/v12.13.1/bin/node
; cwd = /home/jfg/perso/reactnative/test/rnvtest/test7
; HOME = /home/jfg
; Run `npm config ls -l` to show all defaults.
`

in my env node12, I just try to do your same commands, 
`react-native init foobar --version 0.64.2` => ok
`npm install react-native-usb-serialport` => KO

same problem as previously mentionned

Probably I do something wrong, but I don't understand what  I'm new in React Native, but this step seems to be simple
Thanks for your help

**Comment by flyskywhy** [comment]
Ref to https://github.com/lostpebble/pullstate/issues/101#issuecomment-792260716 , you can try

    use npm version which is below 7

or

    npm install react-native-usb-serialport --legacy-peer-deps

and tell me the result.

**Comment by requiem-projects** [comment]
with legacy-peer-deps, it seems to install
Thanks

**Comment by lr210** [comment]
> According to npm semver rule, `^` is compatible with 0.59.0 and 0.64.2, so this issue strange.

Unfortunately because react native is still version 0, minor versions are considered to be incompatible with each other even when the `^` is used
