### ISSUE TITLE
Update Build Configuration for Compatibility with Modern Android SDK and Gradle Versions

### ISSUE THREAD

**Issue by kleepier9** [flyskywhy/react-native-usb-serialport#21]
Today, I encountered a problem while integrating react-native-usb-serialport@3.0.0 into a project that uses updated build configurations, specifically requiring modern compileSdkVersion, buildToolsVersion, and gradle versions.

Problem Description:
The existing build.gradle for react-native-usb-serialport is configured with older versions:

compileSdkVersion set to 28
buildToolsVersion set to "28.0.3"
minSdkVersion set to 16
targetSdkVersion set to 28
gradle version set to 3.3.1
These configurations are incompatible with my project setup, which uses:

compileSdkVersion 35
buildToolsVersion "35.0.0"
minSdkVersion 24
targetSdkVersion 34
gradle version 8.6.0
Resolution:
To resolve this, I updated build.gradle in node_modules/react-native-usb-serialport to match my project configuration. Here is the diff:

diff
Copy code
diff --git a/node_modules/react-native-usb-serialport/android/build.gradle b/node_modules/react-native-usb-serialport/android/build.gradle
index 6d6aa50..75f9013 100644
--- a/node_modules/react-native-usb-serialport/android/build.gradle
+++ b/node_modules/react-native-usb-serialport/android/build.gradle
@@ -1,20 +1,19 @@
-
 buildscript {
     repositories {
         google()
-        maven{ url "https://maven.aliyun.com/nexus/content/groups/public" }
+        maven { url "https://maven.aliyun.com/nexus/content/groups/public" }
     }
 
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.3.1'
+        classpath 'com.android.tools.build:gradle:8.6.0'
     }
 }
 
 apply plugin: 'com.android.library'
 
 android {
-    compileSdkVersion 28
-    buildToolsVersion "28.0.3"
+    compileSdkVersion 35
+    buildToolsVersion "35.0.0"
 
     compileOptions {
         sourceCompatibility JavaVersion.VERSION_1_8
@@ -22,8 +21,8 @@ android {
     }
 
     defaultConfig {
-        minSdkVersion 16
-        targetSdkVersion 28
+        minSdkVersion 24
+        targetSdkVersion 34
         versionCode 1
         versionName "1.0"
     }

Request:
Could you please consider updating the library's build.gradle file to align with more recent Android build requirements? This change would help avoid issues with modern project configurations and make the library more compatible with current Android development standards.

Thanks again for maintaining this project!

**Comment by flyskywhy** [comment]
I think in many case, `react-native-usb-serialport` is used in old Android device, so for compatible, I will not update these, please patch these in yourself.

**Comment by pke** [comment]
@kleepier9 could you please re-format your patch? Thanks a lot!

**Comment by kleepier9** [comment]
@pke Just to clarify, I haven’t submitted a patch, I only asked a question above. Let me know if you were referring to something else!
