### ISSUE TITLE
Add support for lowercase hex characters when writing hex strings

### ISSUE THREAD

**Issue by shivchawla** [flyskywhy/react-native-usb-serialport#3]
Currently, when using `writeHexString`, only upper case letter are supported because of the check on hex charactes
`public final static String hexChars = "0123456789ABCDEF";`
```
if(Definitions.hexChars.indexOf(hex.substring(0, 1)) == -1 || Definitions.hexChars.indexOf(hex.substring(1, 1)) == -1) {
     return;
}
```

Possible fix: `public final static String hexChars = "0123456789ABCDEFabcdef";`

**Comment by flyskywhy** [comment]
2.3.1 support it :stuck_out_tongue:
