### ISSUE TITLE
WriteString error

### ISSUE THREAD

**Issue by MrTVDEV** [flyskywhy/react-native-usb-serialport#4]
Hello,

When I do "RNSerialport.writeString("Hello");",
I get the error RNSerialport.writeString got 1 arguments, expected 2 .

Have you ever had the error? I really don't see where it can come from.

Thank you in advance.

**Comment by flyskywhy** [comment]
As I described in README.md that fork diff from react-native-serialport:
```
-  RNSerialport.writeString('HELLO');
+  RNSerialport.writeString('/dev/bus/usb/001/007', 'HELLO');
```
