### ISSUE TITLE
write string error

### ISSUE THREAD

**Issue by alisaya10** [flyskywhy/react-native-usb-serialport#5]
hi dear i **connected** to the device and i **get the content too** but when i want to write string its give me this error

i try also to connect with Auto-Connection i click on send but it doesnt give an error but still doesnt send to device

**13 | There is no connection**

this is my code to send to the device 

```
  handleSendButton = () => {
    let command = Buffer.Buffer.from([43, 0, 4, 0, 1, 1, 0]);
    command = command.toString();
    console.log(command);
    RNSerialport.writeString('/dev/bus/usb/001/007', command);
  };
```

**Comment by flyskywhy** [comment]
Is `Buffer.Buffer` a typo?

And what's the result of `console.log(command)`?

**Comment by alisaya10** [comment]
no i convert my message to the buffer with buffer library and send it to the device as string i try also without code above like bellowbut still give me the same result

`RNSerialport.writeString('/dev/bus/usb/001/007', "setTrue");`

with this code i convert my byte array to the buffer string and send to the device 

```
  handleSendButton = () => {
    let command = Buffer.Buffer.from([43, 0, 4, 0, 1, 1, 0]);
    command = command.toString();
    console.log(command);
    RNSerialport.writeString('/dev/bus/usb/001/007', command);
  };
```

the result of the console looks like this
+♦☺☺

and give some char that the console does not recognized

**Comment by flyskywhy** [comment]
I have no right device on hand to debug `writeString`, so I suggest you to convert string to bytes and use `writeBytes` first, like below:

    let command = Array.from("setTrue", (x) => x.charCodeAt(0)); // ref to https://gist.github.com/lihnux/2aa4a6f5a9170974f6aa
    RNSerialport.writeBytes('/dev/bus/usb/001/007', command);
