### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by wailin0** [flyskywhy/react-native-usb-serialport#7]
when i try to build i got this error
> Task :app:checkDebugDuplicateClasses FAILED

**Comment by flyskywhy** [comment]
Which class is "Duplicate"? Please paste more context here.

**Comment by wailin0** [comment]
ed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules jetified-guava-20.0 (com.google.guava:guava:20.0) and jetified-listenable
future-1.0 (com.google.guava:listenablefuture:1.0)

**Comment by flyskywhy** [comment]
It's your project specific issue, pure RN 0.63.2 project is OK.

I just guess a solution for your project, maybe you can try

disable (or remove?)  some module in your project that include "com.google.guava:listenablefuture"

or

in `node_modules/react-native-usb-serialport/android/build.gradle` , comment(remove) the line 
```
implementation 'com.google.guava:guava:20.0'
```

**Comment by NqCompiler** [comment]
You can add this to your `android/app/bundle.gradle` dependencies
`implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'`

Background: apparently Google knows about this bug and made a special package to fix this issue

**Comment by flyskywhy** [comment]
Thanks @NqCompiler

**Comment by lr210** [comment]
Personally I did not know how to implement the fix suggested by NqCompiler because my app is built using Expo EAS and so does not have a `bundle.gradle`. I was able to fork this library and remove the dependency on Guava to get around the issue. It looks like there is only one function that is used from Guava which is UnsignedBytes.toInt (a one line function)

**Comment by flyskywhy** [comment]
@lr210 waiting your PR 😝

**Comment by flyskywhy** [comment]
> Personally I did not know how to implement the fix suggested by NqCompiler because my app is built using Expo EAS and so does not have a `bundle.gradle`. I was able to fork this library and remove the dependency on Guava to get around the issue. It looks like there is only one function that is used from Guava which is UnsignedBytes.toInt (a one line function)

@lr210 now `react-native-usb-serialport@2.3.5` did it :yum:
