### ISSUE TITLE
Problem of reading serial data from Arduino Uno

### ISSUE THREAD

**Issue by jangminhyeok** [flyskywhy/react-native-usb-serialport#8]
First of all, Thank you for the library. It is very useful and the best updated version of all.
I tried to read serial data from Arduino Uno which is CH34X clone board.

1. Convert "SerialportGateway.js" class component to functional component
2. "doInit" -> listen to "onReadData"
3. "doDestroy"

Arduino Uno's firmware is uploaded like shown below.

void setup() {
  Serial.begin(9600);
}

void loop() {
  Serial.println(123);
  delay(500);
}

the result of onReadData is shown like this. (from console, adb logcat)

08-18 04:28:36.612 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.614 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.617 14446 14724 I CH34xSerialDevice: Control Transfer Response: 2
08-18 04:28:36.619 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.621 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.623 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.625 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.628 14446 14724 I CH34xSerialDevice: Control Transfer Response: 2
08-18 04:28:36.630 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.632 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.634 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.637 14446 14724 I CH34xSerialDevice: Control Transfer Response: 2
08-18 04:28:36.639 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.641 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.644 14446 14724 I CH34xSerialDevice: Control Transfer Response: 2
08-18 04:28:36.646 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.649 14446 14724 I CH34xSerialDevice: Control Transfer Response: 2
08-18 04:28:36.651 14446 14724 I CH34xSerialDevice: Control Transfer Response: 0
08-18 04:28:36.656 14446 14546 I ReactNativeJS: { linuxDevPath: '/dev/bus/usb/001/002',
08-18 04:28:36.656 14446 14546 I ReactNativeJS:   valueArray: '0618781E981E9880' }
08-18 04:28:36.695 14446 14546 I ReactNativeJS: '/dev/bus/usb/001/002', 'USB serialPort connected'
08-18 04:28:38.207 14446 14546 I ReactNativeJS: { linuxDevPath: '/dev/bus/usb/001/002',
08-18 04:28:38.207 14446 14546 I ReactNativeJS:   valueArray: '000000000000000000000000000000' }
08-18 04:28:38.713 14446 14546 I ReactNativeJS: { linuxDevPath: '/dev/bus/usb/001/002',
08-18 04:28:38.713 14446 14546 I ReactNativeJS:   valueArray: '000000000000000000000000000000' }
08-18 04:28:39.028 14446 14546 I ReactNativeJS: SerialportGateway is destroyed.
08-18 04:28:39.084 14446 14546 I ReactNativeJS: USB service stopped

I have no idea what is the problem in here. Would you suggest any opinion about this problem please?

**Comment by flyskywhy** [comment]
Why you tell me your Arduino Uno embed CH34X? Because for example, board A running react-native-usb-serialport embed a CH34X serial port, board B as Arduino embed a whatever serial port, then A connected B with serial port wire.

So if the reason you tell me that Arduino Uno embed CH34X, is that you are running react-native-usb-serialport in Arduino Uno, then why you `Serial.println(123)` in Arduino Uno (to test without serial port wire)?

Or I misunderstand, you just means to use Arduino Uno to simulate (the "clone" meaning?) as a CH34X?

PS: do you `RNSerialport.connectDevice(path, 9600);` in `SerialportGateway.js`?

And react-native-usb-serialport runs well on my Android board with USB CH34X :yum:

**Comment by jangminhyeok** [comment]
oh my god. I'm so sorry and thank you so much.
there was a mistake in my code which you suggested "RNSerialport.connectDevice(path, 9600);".
I didn't change the baudrate to 9600. It was 115200.

btw, my project is implementing the Arduino GUI Program's serial monitor in react native app. The connection is between smartphone and arduino board with OTG-USB Cable.

The reason why I mentioned 'CH34X' of Arduino Uno is there was a connection or sync problem with 'not clone board (cdc-acm)'. so I thought I should mention it correctly.

you saved my day. thank you so much again.
